name: Build ThorVG

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "ThorVG tag"
        required: true
        type: string


jobs:
  build:
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        # Todo properly dispatch this
        # os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v7
        with:
          python-version: '3.x'
      
      - name: Install Meson and Ninja
        run: python -m pip install meson ninja

      - uses: actions/checkout@v7

      - uses: actions/checkout@v7
        with:
          repository: thorvg/thorvg
          ref: ${{ inputs.tag }}
          path: thorvg

      - name: Configure
        working-directory: thorvg
        run: meson setup build "-Dengines=cpu,gl" -Dstatic=true -Dbuildtype=release -Ddefault_library=static

      - name: Build
        working-directory: thorvg
        run: meson compile -C build

      - name: Package
        env:
          TAG: ${{ inputs.tag }}
          PLATFORM: ${{ runner.os }}
          # ARCH: ${{ runner.arch }}
        run: python Scripts/ci.py

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ inputs.tag }}
        run: |
          gh release create "$TAG" artifacts/* \
            --title "ThorVG $TAG build" \
            --generate-notes
